source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "PrebidMobileDemo" do
  pod 'PrebidMobileFS', :git => 'https://github.com/freestarcapital/Freestar-Prebid-Mobile-iOS.git'

  target "PrebidMobileDemoTests" do
    inherit! :search_paths
  end
end
