source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'
use_frameworks!
install! 'cocoapods', :integrate_targets => false

target "PrebidMobileFS" do
  pod 'FSCache'

  target "PrebidMobileFSTests" do
    inherit! :search_paths
  end
end
