source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "PrebidMobile" do
  pod 'FSCache', :git => 'https://github.com/freestarcapital/FSCache.git'

  target "PrebidMobileTests" do
    inherit! :search_paths
  end
end
