source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target "PrebidMobileFS" do
  pod 'FSCache'

  target "PrebidMobileFSTests" do
    inherit! :search_paths
  end
end
